In [1]:
! python -m pip install "pymongo[srv]"

Requirement already satisfied: pymongo[srv] in c:\Python313\Lib\site-packages (3.12.0)
Requirement already satisfied: dnspython<2.0.0,>=1.16.0 in c:\Python313\Lib\site-packages (from pymongo[srv]) (1.16.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pymongo 
import pandas as pd 
df = pd.read_csv("twitter-stocks.csv.csv")
df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-11-07,45.099998,50.090000,44.000000,44.900002,44.900002,117701670.0
1,2013-11-08,45.930000,46.939999,40.685001,41.650002,41.650002,27925307.0
2,2013-11-11,40.500000,43.000000,39.400002,42.900002,42.900002,16113941.0
3,2013-11-12,43.660000,43.779999,41.830002,41.900002,41.900002,6316755.0
4,2013-11-13,41.029999,42.869999,40.759998,42.599998,42.599998,8688325.0
5,2013-11-14,42.340000,45.669998,42.240002,44.689999,44.689999,11099433.0
6,2013-11-15,45.250000,45.270000,43.430000,43.980000,43.980000,8010663.0
7,2013-11-18,43.500000,43.950001,40.849998,41.139999,41.139999,12810624.0
8,2013-11-19,41.389999,41.900002,40.000000,41.750000,41.750000,7436616.0
9,2013-11-20,41.400002,41.750000,40.509998,41.049999,41.049999,5767325.0

In [13]:
# lets convert it into dict 
data_dict = df.to_dict("records")

In [23]:
project_name = "twitterSTock"
collection_name = "twitterSTockCollection"
collection_url = "mongodb+srv://ramansarkar400rs_db_user:M0JIO64HNbOd2zKq@cluster0.hraojed.mongodb.net/?appName=Cluster0"

In [24]:
# now connect to the mongo db and create a database and collection and insert the data into it
client = pymongo.MongoClient(collection_url)
collection = client[project_name]
name = collection[collection_name]
rec = name.insert_many(data_dict)

In [25]:
df = pd.DataFrame(list(name.find()))

In [26]:
df.head(10)

,_id,Date,Open,High,Low,Close,Adj Close,Volume
0,6a59a71cfae5702183704ee6,2013-11-07,45.099998,50.090000,44.000000,44.900002,44.900002,117701670.0
1,6a59a71cfae5702183704ee7,2013-11-08,45.930000,46.939999,40.685001,41.650002,41.650002,27925307.0
2,6a59a71cfae5702183704ee8,2013-11-11,40.500000,43.000000,39.400002,42.900002,42.900002,16113941.0
3,6a59a71cfae5702183704ee9,2013-11-12,43.660000,43.779999,41.830002,41.900002,41.900002,6316755.0
4,6a59a71cfae5702183704eea,2013-11-13,41.029999,42.869999,40.759998,42.599998,42.599998,8688325.0
5,6a59a71cfae5702183704eeb,2013-11-14,42.340000,45.669998,42.240002,44.689999,44.689999,11099433.0
6,6a59a71cfae5702183704eec,2013-11-15,45.250000,45.270000,43.430000,43.980000,43.980000,8010663.0
7,6a59a71cfae5702183704eed,2013-11-18,43.500000,43.950001,40.849998,41.139999,41.139999,12810624.0
8,6a59a71cfae5702183704eee,2013-11-19,41.389999,41.900002,40.000000,41.750000,41.750000,7436616.0
9,6a59a71cfae5702183704eef,2013-11-20,41.400002,41.750000,40.509998,41.049999,41.049999,5767325.0